# Generated by Django 5.0 on 2023-12-25 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('address_1', models.CharField(max_length=100)),
                ('address_2', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('total_seats', models.IntegerField()),
                ('x1_tables', models.IntegerField()),
                ('x2_tables', models.IntegerField()),
                ('x4_tables', models.IntegerField()),
                ('x6_tables', models.IntegerField()),
                ('x10_communal', models.IntegerField()),
                ('is_veg', models.BooleanField()),
                ('has_bar', models.BooleanField()),
                ('has_private_dining', models.BooleanField()),
                ('has_catering', models.BooleanField()),
                ('promo_scheme', models.TextField()),
                ('scheme_start_date', models.DateField()),
                ('scheme_end_date', models.DateField()),
                ('promo_credits', models.IntegerField()),
                ('service_start_time', models.TimeField()),
                ('service_end_time', models.TimeField()),
                ('emergency_stop', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('is_deleted', models.BooleanField()),
            ],
        ),
    ]
