# Generated by Django 5.0 on 2023-12-26 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurants', '0003_menuitems_itemdetails_itemimages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemDetails',
            new_name='ItemDetail',
        ),
        migrations.RenameModel(
            old_name='ItemImages',
            new_name='ItemImage',
        ),
        migrations.RenameModel(
            old_name='MenuItems',
            new_name='MenuItem',
        ),
        migrations.CreateModel(
            name='RestaurantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='restaurant_images/')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurants.restaurant')),
            ],
        ),
    ]
